Sun, Aug 30 00:00 update configs

diff --git a/bin/lab-gen b/bin/lab-gen
--- a/bin/lab-gen
+++ b/bin/lab-gen
@@ -1,7 +1,5 @@
 #!/bin/bash
 
-source student.env
-
 # Display Help
 
 usage() {
@@ -14,30 +12,28 @@ OPTIONS:
 EOF
 }
 
+if [ $# -gt 3 ]; then
+  usage
+  exit 1
+fi
+
 if [ $# -eq 0 ]; then 
   current_path=$PWD
 
   courseNumber=$(echo "$current_path" | sed -E 's|.*uni/[^0-9]*([0-9]+).*|\1|')
-  work_type=$(echo $current_path | sed -E "s|.*/||")
+  workType=$(echo $current_path | sed -E "s|.*/||")
   discipline=$(echo "$current_path" | sed -E 's|.*uni/([0-9]+/)+([^/]+).*|\2|')
   number=$(echo "$current_path" | sed -E 's|.*lab([0-9]+).*|\1|')
+else
+  discipline=$1
+  workType=$2
+  number=$3
 fi
 
-if [ $# -gt 2 ]; then
-  usage 
-  exit 1
-fi
-
-declare -i number=$1
-
-prefix=
-
-shift
-
-if [ -z "$prefix" ]; then
+if [ -z "$discipline" ] || [ -z "$work_type" ] || [ -z "$number" ]; then
   usage
-  echo
-  echo "Fail: template is required"
+  echo -e "\nFail: Cannot determine discipline, type, or number."
+  exit 1
 fi
 
 template_path="$UNI/.templates/"
@@ -75,6 +71,6 @@ body=$listings"\n\\\clearpage\n# Рисунки\n$figures"
 
 sed -i "s|NUMBER|$number|g;
 s|VARIANT|$variant|g;
-s|TYPE|\\$type_command|g;
+s|TYPE|\\$workType|g;
 s|BODY|${body}|g;
 s|DISCIPLINE|$discipline|g" "$filename"
